name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-chrome:
    name: Run Playwright Tests on Chrome
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests on Chrome
        run: npx playwright test --project=chromium
        env:
          CORRECT_EMAIL_ADDRESS: ${{ secrets.CORRECT_EMAIL_ADDRESS }}
          CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
      - name: Generate Allure Report for Chrome
        run: allure generate allure-results --clean -o allure-report-chrome
      - name: Upload Playwright Report as Artifact for Chrome
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-chrome
          path: playwright-report/
          retention-days: 30
      - name: Upload Allure Report as Artifact for Chrome
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report-chrome
          path: allure-report-chrome/
          retention-days: 30

  test-firefox:
    name: Run Playwright Tests on Firefox
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests on Firefox
        run: npx playwright test --project=firefox
        env:
          CORRECT_EMAIL_ADDRESS: ${{ secrets.CORRECT_EMAIL_ADDRESS }}
          CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
      - name: Generate Allure Report for Firefox
        run: allure generate allure-results --clean -o allure-report-firefox
      - name: Upload Playwright Report as Artifact for Firefox
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-firefox
          path: playwright-report/
          retention-days: 30
      - name: Upload Allure Report as Artifact for Firefox
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report-firefox
          path: allure-report-firefox/
          retention-days: 30

  generate-deploy-allure-report:
    name: Generate and Deploy Allure Report to GitHub Pages
    needs: [test-chrome, test-firefox]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout gh-pages for Allure report history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report
