name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-chromium:
    name: Run Playwright Tests on Chromium
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests on Chromium
        run: npm run test:chromium
        env:
          CI: true
          CORRECT_EMAIL_ADDRESS: ${{ secrets.CORRECT_EMAIL_ADDRESS }}
          CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
      - name: Generate Allure Report for Chromium
        run: npm run allure:generate
      - name: Archive Playwright Reports for Chromium
        uses: actions/upload-artifact@v2
        with:
          name: playwright-reports-chromium
          path: playwright-report/
          retention-days: 30
      - name: Archive Allure Report for Chromium
        uses: actions/upload-artifact@v2
        with:
          name: allure-report-chromium
          path: allure-report/
          retention-days: 30

  test-firefox:
    name: Run Playwright Tests on Firefox
    runs-on: ubuntu-latest
    needs: test-chromium
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests on Firefox
        run: npm run test:firefox
        env:
          CI: true
          CORRECT_EMAIL_ADDRESS: ${{ secrets.CORRECT_EMAIL_ADDRESS }}
          CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
      - name: Generate Allure Report for Firefox
        run: npm run allure:generate
      - name: Archive Playwright Reports for Firefox
        uses: actions/upload-artifact@v2
        with:
          name: playwright-reports-firefox
          path: playwright-report/
          retention-days: 30
      - name: Archive Allure Report for Firefox
        uses: actions/upload-artifact@v2
        with:
          name: allure-report-firefox
          path: allure-report/
          retention-days: 30

  deploy-report:
    name: Deploy Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: [test-chromium, test-firefox]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Download Allure Report Artifact for Chromium
        uses: actions/download-artifact@v2
        with:
          name: allure-report-chromium
          path: allure-report-chromium
      - name: Download Allure Report Artifact for Firefox
        uses: actions/download-artifact@v2
        with:
          name: allure-report-firefox
          path: allure-report-firefox
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_OPENCART}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report
